### ISSUE TITLE
I open the app and cannot see anything. [plain white screen].

### ISSUE THREAD

**Issue by imkin** [harbur/kubernetic-issues#19]
Hi,
I am trying the beta version of the kubernetic. 

I opened the app on my macos and I see white screen with nothing in it. I check on "views and settings" and I see nothing in it too.

I can attach the screenshot but I do not it had help because it is just a plain white screen.

Any suggestions would help.

This is what I see right now btw.

```
angular.js:13920 TypeError: Cannot read property 'current-context' of undefined
    at getCurrentContext (file:///Applications/Kubernetic.app/Contents/Resources/app.asar/app/services/kubectl/kubectl.service.js:1:278)
    at Scope.e.watchKubernetes (file:///Applications/Kubernetic.app/Contents/Resources/app.asar/app/layouts/main/main.controller.js:1:7924)
    at new <anonymous> (file:///Applications/Kubernetic.app/Contents/Resources/app.asar/app/layouts/main/main.controller.js:1:8767)
    at Object.instantiate (file:///Applications/Kubernetic.app/Contents/Resources/app.asar/bower_components/angular/angular.js:4733:14)
    at $controller (file:///Applications/Kubernetic.app/Contents/Resources/app.asar/bower_components/angular/angular.js:10369:28)
    at Object.<anonymous> (file:///Applications/Kubernetic.app/Contents/Resources/app.asar/bower_components/angular-ui-router/release/angular-ui-router.min.js:7:23873)
    at file:///Applications/Kubernetic.app/Contents/Resources/app.asar/bower_components/angular/angular.js:1247:18
    at invokeLinkFn (file:///Applications/Kubernetic.app/Contents/Resources/app.asar/bower_components/angular/angular.js:9934:9)
    at nodeLinkFn (file:///Applications/Kubernetic.app/Contents/Resources/app.asar/bower_components/angular/angular.js:9335:11)
    at compositeLinkFn (file:///Applications/Kubernetic.app/Contents/Resources/app.asar/bower_components/angular/angular.js:8620:13) <div ui-view="" class="ng-scope">(anonymous function) @ angular.js:13920
angular-ui-router.min.js:7 Uncaught Error: Could not resolve 'main.settings.connection' from state 'main.dashboard```

**Comment by vielmetti** [comment]
This might be the same as #15, or related

**Comment by spiddy** [comment]
In this case first check that `kubectl` can access the cluster. This needs to work before using Kubernetic

```
kubectl get nodes
```

Another case is in GCP Clusters (or any other token-credential-based clusters) are not yet supported.

**Comment by spiddy** [comment]
Now Kubernetic checks if `~/.kube/config` exists and provide info in Clusters page if it doesn't how to configure kubectl.
